using UnityEditor;
namespace Pixyz.Toolbox.Editor {

	// THIS SCRIPT IS AUTOGENERATED. PLEASE DO NOT MODIFY OR MOVE IT.
	public static class ToolboxMenuItems {

		[MenuItem("Pixyz/Toolbox/Mesh/Decimate", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Decimate", priority = -20)]
		public static void Adbb5fcb6_346c_400d_a5b0_f5bf9e0403ed() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.DecimateAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Create Collider", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Create Collider", priority = -19)]
		public static void A003dc85e_8102_4c7a_9372_c01f611aca7e() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.CreateColliderAction()); }

		[MenuItem("Pixyz/Toolbox/Colliders/Remove Colliders", priority = 22)]
		[MenuItem("GameObject/Pixyz/Colliders/Remove Colliders", priority = -18)]
		public static void Abc177d24_094c_4c0b_9198_784e1f72c044() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.RemoveCollidersAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Repair", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Repair", priority = -17)]
		public static void Af6d2ed30_b67f_4972_91e4_9edff2e51f9f() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.RepairMeshAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Z-Fighting", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Z-Fighting", priority = -15)]
		public static void A108fc2bf_6807_41b5_8e86_2b42f482f501() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.RemoveZFightingAction()); }

		[MenuItem("Pixyz/Toolbox/Mesh/Remove Hidden", priority = 22)]
		[MenuItem("GameObject/Pixyz/Mesh/Remove Hidden", priority = -14)]
		public static void A86b18110_12c7_4ffa_9c87_bb9b0719a02c() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.RemoveHiddenAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Retopologize", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Retopologize", priority = -13)]
		public static void Af8f0d319_649f_4fc6_9185_c3dcfd336296() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.RetopologizeAction()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Impostor", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Impostor", priority = -12)]
		public static void Af1044dba_95c6_4393_96d2_7592494e4686() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.BakeImpostor()); }

		[MenuItem("Pixyz/Toolbox/Remeshing/Create Billboard", priority = 22)]
		[MenuItem("GameObject/Pixyz/Remeshing/Create Billboard", priority = -12)]
		public static void A27455a8b_49fc_4742_b792_0ff5042200a5() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.GenerateBillboardAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Merge", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Merge", priority = -11)]
		public static void A4d8f59e5_12d0_4c0c_b562_a4916fb182cc() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.Merge()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Combine", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Combine", priority = -10)]
		public static void Abd38e9dd_5b2f_4d11_9376_0ba79b9aee4b() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.CombineAction()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Replace by...", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Replace by...", priority = -9)]
		public static void A25349a7d_210e_480e_b33a_d4d2d6551a82() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.ReplaceBy()); }

		[MenuItem("Pixyz/Toolbox/Hierarchy/Explode", priority = 22)]
		[MenuItem("GameObject/Pixyz/Hierarchy/Explode", priority = -8)]
		public static void A1d07d0e7_ebfe_4cb4_babe_b6ebfad5a31d() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.ExplodeSubmeshesAction()); }

		[MenuItem("Pixyz/Toolbox/Pivot/Move Pivot", priority = 22)]
		[MenuItem("GameObject/Pixyz/Pivot/Move Pivot", priority = -7)]
		public static void A2fef91b4_e7b9_4ad0_86c6_d44f2b45de86() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.MovePivotAction()); }

		[MenuItem("Pixyz/Toolbox/Normals/Flip Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Flip Normals", priority = -6)]
		public static void A3f44718b_f50c_4305_863d_dcd55209dff8() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.FlipNormals()); }

		[MenuItem("Pixyz/Toolbox/Normals/Create Normals", priority = 22)]
		[MenuItem("GameObject/Pixyz/Normals/Create Normals", priority = -5)]
		public static void Aa79fb4f7_e135_4d2b_9dbd_88c0deb9158f() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.CreateNormals()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs", priority = -4)]
		public static void Aeb72fec2_4bcb_4ca3_bbfe_74a1f0ddf020() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.CreateUVs()); }

		[MenuItem("Pixyz/Toolbox/UVs/Create UVs for Lightmaps", priority = 22)]
		[MenuItem("GameObject/Pixyz/UVs/Create UVs for Lightmaps", priority = -3)]
		public static void Ab4406f77_5214_4488_ae96_071460e5e88f() { Toolbox.RunToolboxAction(new Pixyz.Toolbox.Editor.CreateLightmapUVs()); }

	}
}